#!/bin/bash

set -u
shopt -s extglob

#Color variables:
# https://gist.github.com/JBlond/2fea43a3049b38287e5e9cefc87b2124
# `read -p` printf workaround:
# read -p "$(printf "${BLUE}Enter your username: ${RESET}")" userName
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
BLUE='\e[34m'
WHITE='\e[37m'
PURPLE='\e[35m'
BOLD='\e[1m'
RESET='\e[0m'

locUser="$USER"
runitTest="$(ps -p 1 -o comm=)"

evdiRepo="https://github.com/DisplayLink/evdi.git"
evdiGitPath="$(find /home/$locUser -type d -name "evdi" 2>/dev/null)"
evdiTarPath="${evdiGitPath%/*}"
evdiGitMain=""
evdiGitTag=""

# To-Do: sudo /usr/bin/displaylink-installer version 2>&1 | grep -Eoi "DisplayLink Linux Software [0-9+].[0-9]+.[0-9]+"
# Current DisplayLink Download: https://www.synaptics.com/sites/default/files/exe_files/2026-06/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.3-EXE.zip
# Note: Will pull DisplayLink if not downloaded already to /home/$USER/Downloads
displayLinkDl="https://www.synaptics.com/sites/default/files/exe_files/2026-06/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.3-EXE.zip"
displayStatus=""
displayLinkFullName=""
displayLinkPath=""
displayLinkName=""
displayLinkNameFix=""
displayLinkVer=""
displayLinkTarget=""
displayLinkFileDir=""
displayLinkInstallDir=""
readarray -t dispArr < <(echo "$(find /home/$locUser -type f -name "DisplayLink*.zip")")
if (( "${#dispArr[@]}" > 1 )); then 
	displayLinkFullName="${dispArr[0]}"
	displayLinkPath="${displayLinkFullName%/*}"
	displayLinkName="${displayLinkFullName##*/}"
	displayLinkNameFix="'${displayLinkName//\'/\'\\\'\'}'"
	displayLinkVer="$(grep -Eo "[0-9]+\.[0-9]+" <<< $displayLinkNameFix)"
	displayLinkTarget="displaylink_${displayLinkVer}"
	displayLinkFileDir="${displayLinkPath}/${displayLinkTarget}"
	displayLinkInstallDir="/opt/${displayLinkTarget}"
fi

evdiTest="$(lsmod | grep -Eio "evdi" | head -1)"
displayInstallerTest="/usr/bin/displaylink-installer"
installDec=""

downloadEvdiFile="false"
downloadDisplayFile="false"

clear

printf "${BLUE}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
printf "${BLUE}:::${RESET} ${WHITE}DisplayLink Installer${RESET}\n"
printf "${BLUE}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n"

if [[ -n $evdiTest && -f $displayInstallerTest ]]; then 
	printf "${RED}>>> WARNING:${RESET} ${WHITE}DisplayLink and EVDI kernel modules are already installed on your system.${RESET}\n"
	printf "${RED}>>>${RESET} ${WHITE}If you want to first uninstall (RECOMMENDED), please uninstall via your package manager or run this command:${RESET}\n"
	printf "${RED}>>>${RESET} ${WHITE}sudo displaylink-installer uninstall${RESET}\n"
	read -p "$(printf "${BLUE}:::${RESET} ${WHITE}Proceed with installation? [Y/n]: ${RESET}")" installDec
	if [[ -z $installDec ]]; then 
		installDec="y"
	fi
	firstChar="${installDec:0:1}"
	installDec="${firstChar,}"
	printf "${BLUE}:::${RESET} ${WHITE}Installation choice: ${installDec}${RESET}\n"
else 
	installDec="y"
fi

evdi_git_tag_util() {
	if [[ -z $evdiGitPath ]]; then
		printf "${BLUE}:::${RESET} ${WHITE}Cloning ${evdiRepo} for you.${RESET}\n"
		rm -rf /tmp/evdi
		rm -f /tmp/evdi.tar.gz
		git clone -q "${evdiRepo}" /tmp/evdi 
		evdiGitPath=$(find /tmp -maxdepth 1 -type d -name "evdi" 2>/dev/null)
		evdiTarPath="${evdiGitPath%/*}"
		downloadEvdiFile="true"
	fi

	if [[ ! -d $evdiGitPath ]]; then 
		printf "${RED}>>> Error:${RESET} ${WHITE}Could not clone https://github.com/DisplayLink/evdi${RESET}\n" >&2
		exit 1
	fi

	cd "$evdiGitPath"
	git pull -q
	evdiGitMain="$(git rev-parse --abbrev-ref origin/HEAD | cut -d/ -f2)"

	read -p "$(printf "${GREEN}:::${RESET} ${WHITE}Install with the latest EVDI version (RECOMMENDED)? To choose a specific version, enter ${RESET}${RED}'n'${RESET} ${WHITE}[Y/n]: ${RESET}")" evdiLatest
	firstChoice="${evdiLatest:0:1}"
	evdiLatest="${firstChoice,}"

	if [[ $evdiLatest == 'n' ]]; then
		local -i runSel
		local -a evdiArr
		local -i ind
		local -i runInd
		local runPat=""
		local -i arrInd
		local -a runPart

		readarray -t evdiArr < <(echo "$(git describe --tags $(git rev-list --tags --max-count=200) | grep -Eow '^v?[0-9]+\.[0-9]+\.[0-9]+($)')")
		while [[ -z $evdiGitTag ]]; do
			for ind in "${!evdiArr[@]}"; do
				runInd="ind + 1"
				printf "${BLUE}::: ${runInd})${RESET} ${WHITE}${evdiArr[$ind]}${RESET}\n"

				if [[ -z $runPat ]]; then
					runPat="${runInd}"
				else
					runPat="${runPat}|${runInd}"
				fi
			done
	
			if (( "${#evdiArr[@]}" > 1 )); then
				read -p "$(printf "${GREEN}:::${RESET} ${WHITE}Enter your choice [1-${runInd}]: ${RESET}")" runSel
			else
				read -p "$(printf "${GREEN}:::${RESET} ${WHITE}Enter your choice [1]: ${RESET}")" runSel
			fi
			case $runSel in
				@($runPat))
					arrInd="runSel - 1"
					read -ra runPart <<< "${evdiArr[$arrInd]}"
					evdiGitTag="${runPart[0]}"
			;;
				*)
					printf "${RED}>>>${RESET} ${WHITE}Please choose an EVDI version to install.${RESET}\n"
					evdiGitTag=''
			;;
			esac
		done
	else 
		evdiGitTag="$(git describe --tags $(git rev-list --tags --max-count=1))"
	fi

	if [[ -z $evdiGitTag ]]; then
		printf "${RED}>>>${RESET} ${WHITE}There are no tags for this repo. Exiting.${RESET}\n" >&2
		if [[ $downloadEvdiFile == "true" ]]; then 
			printf "${RED}>>>${RESET} ${WHITE}Removing: ${evdiGitPath}${RESET}\n"
			rm -rf "$evdiGitPath"
		fi			
		exit 1
	fi

	git fetch -q --tags && git checkout -b "$evdiGitTag" "$evdiGitTag" 2>/dev/null
	tar -czf "${evdiTarPath}/evdi.tar.gz" .
	git checkout -q "$evdiGitMain"
	git branch -q -d "$evdiGitTag"

	if [[ ! -f "${evdiTarPath}/evdi.tar.gz" ]]; then 
		printf "${RED}>>>${RESET} ${WHITE}${evdiTarPath}/evdi.tar.gz does not exist. Exiting.${RESET}\n" >&2
		if [[ $downloadEvdiFile == "true" ]]; then 
			printf "${RED}>>>${RESET} ${WHITE}Removing: ${evdiGitPath}${RESET}\n"
			rm -rf "$evdiGitPath"
		fi			
		exit 1
	fi

}

unzip_displaylink() {
	local wgetTest="$(which wget 2>/dev/null)"
	local unzipTest="$(which unzip 2>/dev/null)"
	local failTest="false"

	if [[ -z $wgetTest ]]; then
		printf "${RED}>>> Error:${RESET} ${WHITE}Please install ${RESET}${RED}'wget'${RESET}. ${WHITE}Exiting.${RESET}\n" >&2
		failTest="true"
	fi

	if [[ -z $unzipTest ]]; then 
		printf "${RED}>>> Error:${RESET} ${WHITE}Please install ${RESET}${RED}'unzip'${RESET}. ${WHITE}Exiting.${RESET}\n" >&2
		failTest="true"
	fi

	if [ "$failTest" = "true" ]; then
		printf "${RED}>>>${RESET} ${WHITE}Cleaning up files. Exiting.${RESET}\n"
		if [[ $downloadEvdiFile == "true" ]]; then 
			printf "${RED}>>>${RESET} ${WHITE}Removing: ${evdiTarPath}/evdi.tar.gz${RESET}\n"
			rm -f "${evdiTarPath}/evdi.tar.gz"
			printf "${RED}>>>${RESET} ${WHITE}Removing: ${evdiGitPath}${RESET}\n"
			rm -rf "$evdiGitPath"
		fi
		exit 1
	fi

	if [[ -z $displayLinkFullName ]]; then
		printf "${BLUE}:::${RESET} ${WHITE}Downloading DisplayLink for you.${RESET}\n"
		wget -q -P /tmp/ "$displayLinkDl"
		displayLinkFullName="$(find /tmp -type f -name "DisplayLink*.zip" 2>/dev/null)"
		downloadDisplayFile="true"

		if [[ ! -f $displayLinkFullName ]]; then 
			printf "${RED}>>> Error:${RESET} ${WHITE}Could not download DisplayLink.${RESET}\n" >&2
			printf "${RED}>>>${RESET} ${WHITE}Cleaning up files. Exiting.${RESET}\n"

			if [[ $downloadEvdiFile == "true" ]]; then 
				printf "${RED}>>>${RESET} ${WHITE}Removing: ${evdiTarPath}/evdi.tar.gz${RESET}\n"
				rm -f "${evdiTarPath}/evdi.tar.gz"
				printf "${RED}>>>${RESET} ${WHITE}Removing: ${evdiGitPath}${RESET}\n"
				rm -rf "$evdiGitPath"
			fi
			exit 1
		fi
	else 
		if (( "${#dispArr[@]}" > 1 )); then
			printf "${GREEN}:::${RESET} ${WHITE}Loading user downloaded versions of the DisplayLink installer:${RESET}\n"
			displayLinkFullName=""
			local -i runSelDisp
			local -i indDisp
			local -i runIndDisp
			local runPatDisp=""
			local -i arrIndDisp
			local -a runPartDisp

			while [[ -z $displayLinkFullName ]]; do
				for indDisp in "${!dispArr[@]}"; do
					runIndDisp="indDisp + 1"
					printf "${BLUE}::: ${runIndDisp})${RESET} ${WHITE}${dispArr[$indDisp]}${RESET}\n"

					if [[ -z $runPatDisp ]]; then
							runPatDisp="${runIndDisp}"
					else
							runPatDisp="${runPatDisp}|${runIndDisp}"
					fi
				done

				read -p "$(printf "${GREEN}:::${RESET} ${WHITE}Enter your choice for the local version of DisplayLink to install [1-${runIndDisp}]: ${RESET}")" runSelDisp
				
				case $runSelDisp in
					@($runPatDisp))
						arrIndDisp="runSelDisp - 1"
						read -ra runPartDisp <<< "${dispArr[$arrIndDisp]}"
						displayLinkFullName="${runPartDisp[@]}"
				;;
					*)
						printf "${RED}>>>${RESET} ${WHITE}Please choose a DisplayLink version to install.${RESET}\n"
						displayLinkFullName=""
				;;
				esac
			done
		fi
	fi
	unzip "$displayLinkFullName" -d "$displayLinkFileDir"
	displayLinkPath="${displayLinkFullName%/*}"
	displayLinkName="${displayLinkFullName##*/}"
	displayLinkNameFix="'${displayLinkName//\'/\'\\\'\'}'"
	displayLinkVer="$(grep -Eo "[0-9]+\.[0-9]+" <<< $displayLinkNameFix)"
	displayLinkTarget="displaylink_${displayLinkVer}"
	displayLinkFileDir="${displayLinkPath}/${displayLinkTarget}"
	displayLinkInstallDir="/opt/${displayLinkTarget}"
}


if [[ $installDec != "y" ]]; then
	printf "${RED}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
	printf "${RED}>>>${RESET} ${WHITE}DisplayLink install is exiting.${RESET}\n" >&2
	printf "${RED}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
	exit 1
else
# Heredoc hates your \tab

evdi_git_tag_util

unzip_displaylink

if [[ -z $displayLinkInstallDir ]]; then
	printf "${RED}>>>${RESET} ${WHITE}Installation target directory is missing. Exiting.${RESET}\n" >&2
	exit 1
fi

sudo bash -s "$displayLinkFileDir" "$displayLinkInstallDir" "$locUser" <<'EOF'
	if [ -d "$2" ]; then
		rm -rf "$2"
	fi
	mv "$1" "$2"
	chown -R "$3":"$3" "$2"
EOF

cd "$displayLinkInstallDir"

sudo bash -s "$displayLinkInstallDir" "$locUser" "$RED" "$WHITE" "$RESET" <<'EOF'
	runFile="$(find "$1" -type f -name "*.run" 2>/dev/null)"

	if [[ -z $runFile ]]; then 
		printf "${3}>>>${5} ${4}No DisplayLink run file exists. Exiting.${5}\n" >&2
		exit 1
	fi

	chmod +x "$runFile"
	"$runFile" --noexec --keep
	chown -R "$2":"$2" "$1"
EOF

extractDir="$(find "$displayLinkInstallDir" -maxdepth 1 -type d -name "displaylink-*" 2>/dev/null)"

if [[ -z $extractDir ]]; then
	printf "${RED}>>>${RESET} ${WHITE}No extracted installation directory exists. Exiting.${RESET}\n" >&2
	exit 1
fi

cd "$extractDir"

sudo bash -s "$extractDir" "$evdiTarPath" "$locUser" "$displayLinkInstallDir" "$BLUE" "$WHITE" "$RESET" "$displayLinkFullName" "$evdiGitPath" "$downloadEvdiFile" "$downloadDisplayFile" <<'EOF'
	mv "$2/evdi.tar.gz" "$1/"
	chown -R "$3":"$3" "$4"
	chmod +x "$1/displaylink-installer.sh"
	./displaylink-installer.sh noreboot

	printf "${5}>>>${7} ${6}Cleaning up files and removing: ${4}${7}\n"
	rm -rf "$4"
	if [ "${10}" = "true" ]; then 
		printf "${5}>>>${7} ${6}Removing: ${9}${7}\n"
		rm -rf "$9"
	fi
	if [ "${11}" = "true" ]; then 
		printf "${5}>>>${7} ${6}Removing: ${8}${7}\n"
		rm -f "$8"
	fi 
EOF

displayStatus="$(which displaylink-installer 2>/dev/null)"

if [[ -z $displayStatus ]]; then
	printf "${RED}::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
	printf "${RED}:::${RESET}\n"
	printf "${RED}:::${RESET} ${WHITE}DisplayLink Installer Failed to Install.${RESET}\n"
	printf "${RED}:::${RESET}\n"
	printf "${RED}::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
else 
	printf "${BLUE}::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
	printf "${BLUE}:::${RESET}\n"
	printf "${BLUE}:::${RESET} ${WHITE}DisplayLink Installer Complete${RESET}\n"
	printf "${BLUE}:::${RESET}\n"
	printf "${BLUE}:::${RESET} ${WHITE}You will need to reboot for the EVDI kernel modules to load${RESET}\n"
	if [[ $runitTest == "runit" ]]; then
		printf "${BLUE}:::${RESET} ${WHITE}VOID linux/runit -based distro users: Remember to remove the 'down' service file and restart the 'displaylink-driver' service:${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}cd /var/service/displaylink-driver${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}sudo mv down down.bak${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}sudo sv restart displaylink-driver${RESET}\n"
	else
		printf "${BLUE}:::${RESET} ${WHITE}Systemd -based distro users: Remember to check the status of the 'displaylink' service by running:${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}sudo systemctl status displaylink-driver.service${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}or${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}sudo systemctl status displaylink.service${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}To start the service if not running: ${RESET}\n"
		printf "${BLUE}:::${RESET} ${WHITE}sudo systemctl enable --now <DISPLAYLINK_SERVICE_NAME> ${RESET}\n"
	fi
	printf "${BLUE}::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
fi

# Heredoc still hates your \tab
fi
