#!/bin/bash

#Color variables:
# https://gist.github.com/JBlond/2fea43a3049b38287e5e9cefc87b2124
# `read -p` printf workaround:
# read -p "$(printf "${BLUE}Enter your username: ${RESET}")" userName
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
BLUE='\e[34m'
WHITE='\e[37m'
PURPLE='\e[35m'
BOLD='\e[1m'
RESET='\e[0m'

locUser="$USER"
voidTest="$(cat /etc/os-release | grep -Eo "void" | head -1)"

evdiRepo="https://github.com/DisplayLink/evdi.git"
evdiGitPath="$(find /home/$locUser -type d -name "evdi")"
evdiTarPath="${evdiGitPath%/*}"
evdiGitMain=""
evdiGitTag=""

# Note: Will pull DisplayLink if not downloaded already to /home/$USER/Downloads
displayLinkDl="https://www.synaptics.com/sites/default/files/exe_files/2026-06/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.3-EXE.zip"
displayLinkFullName="$(find /home/$locUser -type f -name "DisplayLink*.zip")"
displayLinkPath="${displayLinkFullName%/*}"
displayLinkName="${displayLinkFullName##*/}"
displayLinkNameFix="'${displayLinkName//\'/\'\\\'\'}'"
displayLinkVer="$(grep -Eo "[0-9]+\.[0-9]+" <<< $displayLinkNameFix)"
displayLinkTarget="displaylink_${displayLinkVer}"
displayLinkFileDir="${displayLinkPath}/${displayLinkTarget}"
displayLinkInstallDir="/opt/${displayLinkTarget}"

# To-Do: sudo /usr/bin/displaylink-installer version 2>&1 | grep -Eoi "DisplayLink Linux Software [0-9+].[0-9]+.[0-9]+"
# Current DisplayLink Download: https://www.synaptics.com/sites/default/files/exe_files/2026-06/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.3-EXE.zip

evdiTest="$(lsmod | grep -Eio "evdi" | head -1)"
displayInstallerTest="/usr/bin/displaylink-installer"
installDec=""

downloadEvdiFile="n"
downloadDisplayFile="n"

clear

printf "${BLUE}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
printf "${BLUE}::${RESET} ${WHITE}DisplayLink Installer${RESET}\n"
printf "${BLUE}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n"

if [[ -n $evdiTest && -f $displayInstallerTest ]]; then 
	printf "${RED}>>> WARNING:${RESET} ${WHITE}DisplayLink and EVDI kernel modules are already installed on your system.${RESET}\n"
	printf "${RED}>>> WARNING:${RESET} ${WHITE}If you want to first uninstall, run: sudo displaylink-installer uninstall${RESET}\n"
	read -p "$(printf "${BLUE}:::${RESET} ${WHITE}Proceed with installing? [Y/n]: ${RESET}")" installDec
	if [[ -z $installDec ]]; then 
		installDec="y"
	fi
	firstChar="${installDec:0:1}"
	installDec="${firstChar,}"
	echo "$installDec"
else 
	installDec="y"
fi

evdi_git_tag_util() {
	if [[ -z $evdiGitPath ]]; then
		printf "${BLUE}::${RESET} ${WHITE}Cloning ${evdiRepo} for you.${RESET}\n"
		rm -rf /tmp/evdi
		git clone "${evdiRepo}" /tmp/evdi 
		evdiGitPath=$(find /tmp -maxdepth 1 -type d -name "evdi")
		evdiTarPath="${evdiGitPath%/*}"
		downloadEvdiFile="y"
	fi
	
	if [[ -n $evdiGitPath ]]; then
		cd "$evdiGitPath"
		git pull
		evdiGitMain="$(git rev-parse --abbrev-ref origin/HEAD | cut -d/ -f2)"
		evdiGitTag="$(git describe --tags $(git rev-list --tags --max-count=1))"
		if [[ -n $evdiGitTag ]]; then
			git fetch --tags && git checkout -b "$evdiGitTag"
			tar -czvf ../evdi.tar.gz .
			git checkout "$evdiGitMain"
			git branch -d "$evdiGitTag"
		else
			printf "${RED}>>>${RESET} ${WHITE}There are no tags for this repo. Exiting.${RESET}\n" >&2
			exit 1
		fi
	else
		printf "${RED}>>> Error:${RESET} ${WHITE}Could not clone https://github.com/DisplayLink/evdi${RESET}\n" >&2
		exit 1
	fi	
}

unzip_displaylink() {
	if [[ -z $displayLinkFullName ]]; then
		wgetTest="$(which wget)"
		displayFile=""
		if [[ -n $wgetTest ]]; then
			printf "${BLUE}::${RESET} ${WHITE}Downloading DisplayLink 6.3 for you.${RESET}\n"
			displayFile="$(wget -q -P /tmp/ ${displayLinkDl})"
			displayLinkFullName="$(find /tmp -type f -name "DisplayLink*.zip")"
			downloadDisplayFile="y"
		else
			printf "${RED}>>> Error:${RESET} ${WHITE}Please install wget. Exiting.${RESET}\n" >&2
			exit 1
		fi

		if [[ -f  $displayLinkFullName ]]; then
			displayLinkPath="${displayLinkFullName%/*}"
			displayLinkName="${displayLinkFullName##*/}"
			displayLinkNameFix="'${displayLinkName//\'/\'\\\'\'}'"
			displayLinkVer="$(grep -Eo "[0-9]+\.[0-9]+" <<< $displayLinkNameFix)"
			displayLinkTarget="displaylink_${displayLinkVer}"
			displayLinkFileDir="${displayLinkPath}/${displayLinkTarget}"
			displayLinkInstallDir="/opt/${displayLinkTarget}"
			unzip "$displayLinkFullName" -d "$displayLinkFileDir"
		else
			printf "${RED}>>> Error:${RESET} ${WHITE}Could not download DisplayLink.${RESET}\n" >&2
			printf "${RED}>>>:${RESET} ${WHITE}Cleaning up files. Exiting.${RESET}\n" >&2
			rm -f "${evdiTarPath}/evdi.tar.gz"
			rm -rf "$$evdiGitPath"
			rm -f "$displayLinkFullName"
			exit 1
		fi
	else 
		unzip "$displayLinkFullName" -d "$displayLinkFileDir"
	fi
}


if [[ $installDec != "y" ]]; then
	printf "${RED}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n" >&2
	printf "${RED}>>>${RESET} ${WHITE}DisplayLink install is exiting.${RESET}\n" >&2
	printf "${RED}:::::::::::::::::::::::::::::::::::::::::::${RESET}\n" >&2
	exit 1
else
# Heredoc hates your \tab

evdi_git_tag_util

unzip_displaylink

if [[ -n $displayLinkInstallDir ]]; then
	sudo bash -s "$displayLinkFileDir" "$displayLinkInstallDir" "$locUser" <<'EOF'
		if [ -d "$2" ]; then
			rm -rf "$2"
		fi
		mv "$1" "$2"
		chown -R "$3":"$3" "$2"
EOF
else
	printf "${RED}>>>${RESET} ${WHITE}Installation target directory is missing. Exiting.${RESET}\n" >&2
	exit 1
fi

cd "$displayLinkInstallDir"

sudo bash -s "$displayLinkInstallDir" "$locUser" "$RED" "$WHITE" "$RESET" <<'EOF'
	runFile="$(find "$1" -type f -name "*.run")"
	if [[ -n $runFile ]]; then
		chmod +x "$runFile"
		"$runFile" --noexec --keep
		chown -R "$2":"$2" "$1"
	else
		printf "${3}>>>${5} ${4}No DisplayLink run file exists. Exiting.${5}\n" >&2
		exit 1
	fi
EOF

extractDir="$(find "$displayLinkInstallDir" -maxdepth 1 -type d -name "displaylink-*")"

if [[ -n $extractDir ]]; then
	cd "$extractDir"
else
	printf "${RED}>>>${RESET} ${WHITE}No extracted installation directory exists. Exiting.${RESET}\n" >&2
	exit 1
fi

sudo bash -s "$extractDir" "$evdiTarPath" "$locUser" "$displayLinkInstallDir" "$RED" "$WHITE" "$RESET" "$displayLinkFullName" "$evdiGitPath" "$downloadEvdiFile" "$downloadDisplayFile" <<'EOF'
	if [ -f "$1/evdi.tar.gz" ]; then
		mv "$1/evdi.tar.gz" "$1/evdi.tar.gz.bak.$(date +%Y%m%d)"
	else
		printf "${5}>>>${7} ${6}${1}/evdi.tar.gz does not exist. Exiting.${7}\n" >&2
		exit 1
	fi	
	if [ -f "$2/evdi.tar.gz" ]; then
		mv "$2/evdi.tar.gz" "$1/"
		chown -R "$3":"$3" "$4"
		chmod +x "$1/displaylink-installer.sh"
		./displaylink-installer.sh
		
		printf "${5}>>>${7} ${6}${1}Removing: ${4}${7}\n" >&2
		rm -rf "$4"
		if [ "$10" == "y" ]; then 
			printf "${5}>>>${7} ${6}${1}Removing: ${9}${7}\n" >&2
			rm -rf "$9"
		fi
		if [ "$11" == "y" ]; then 
			printf "${5}>>>${7} ${6}${1}Removing: ${8}${7}\n" >&2
			rm -f "$8"
		fi 
	else
		printf "${5}>>>${7} ${6}${2}/evdi.tar.gz does not exist. Exiting.${7}\n" >&2
		printf "${5}>>>${7} ${6}${1}Removing: ${4}${7}\n" >&2
		rm -rf "$4"
		if [ "$10" == "y" ]; then 
			printf "${5}>>>${7} ${6}${1}Removing: ${9}${7}\n" >&2
			rm -rf "$9"
		fi
		if [ "$11" == "y" ]; then 
			printf "${5}>>>${7} ${6}${1}Removing: ${8}${7}\n" >&2
			rm -f "$8"
		fi 

		exit 1
	fi
EOF



printf "${BLUE}::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::${RESET}\n"
printf "${BLUE}::${RESET} ${WHITE}DisplayLink Installer Complete${RESET}\n"
printf "${BLUE}::${RESET} ${WHITE}You will need to reboot for the EVDI kernel modules to load${RESET}\n"
if [[ -n $voidTest ]]; then
	printf "${BLUE}::${RESET} ${WHITE}VOID linux/runit -based distro users: Remember to remove the 'down' service file and restart the 'displaylink-driver' service:${RESET}\n"
	printf "${BLUE}::${RESET} ${WHITE}cd /var/service/displaylink-driver${RESET}\n"
	printf "${BLUE}::${RESET} ${WHITE}sudo mv down down.bak${RESET}\n"
	printf "${BLUE}::${RESET} ${WHITE}sudo sv restart displaylink-driver${RESET}\n"
fi
printf "${BLUE}::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::${RESET}\n"

# Heredoc still hates your \tab
fi
